version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    image: web:react
    container_name: react_container
    volumes:
      - ./public:/app/public
      - ./src/styles:/app/src/styles
      - ./src/app:/app/src/app
    networks:
      - backend_network
networks:
  backend_network:
    name: backend_network